/**
 * Generated by Scrooge
 *   version: ?
 *   rev: ?
 *   built at: ?
 */
package ckite.rpc.thrift

import com.twitter.scrooge.{
  ThriftException, ThriftStruct, ThriftStructCodec3}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object AppendEntriesResponseST extends ThriftStructCodec3[AppendEntriesResponseST] {
  val Struct = new TStruct("AppendEntriesResponseST")
  val TermField = new TField("term", TType.I32, 1)
  val TermFieldManifest = implicitly[Manifest[Int]]
  val SuccessField = new TField("success", TType.BOOL, 2)
  val SuccessFieldManifest = implicitly[Manifest[Boolean]]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: AppendEntriesResponseST) {
  }

  override def encode(_item: AppendEntriesResponseST, _oproto: TProtocol) { _item.write(_oproto) }
  override def decode(_iprot: TProtocol): AppendEntriesResponseST = Immutable.decode(_iprot)

  def apply(
    term: Int,
    success: Boolean
  ): AppendEntriesResponseST = new Immutable(
    term,
    success
  )

  def unapply(_item: AppendEntriesResponseST): Option[Product2[Int, Boolean]] = Some(_item)

  object Immutable extends ThriftStructCodec3[AppendEntriesResponseST] {
    override def encode(_item: AppendEntriesResponseST, _oproto: TProtocol) { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): AppendEntriesResponseST = {
      var term: Int = 0
      var _got_term = false
      var success: Boolean = false
      var _got_success = false
      var _done = false
      _iprot.readStructBegin()
      while (!_done) {
        val _field = _iprot.readFieldBegin()
        if (_field.`type` == TType.STOP) {
          _done = true
        } else {
          _field.id match {
            case 1 => { /* term */
              _field.`type` match {
                case TType.I32 => {
                  term = {
                    _iprot.readI32()
                  }
                  _got_term = true
                }
                case _ => TProtocolUtil.skip(_iprot, _field.`type`)
              }
            }
            case 2 => { /* success */
              _field.`type` match {
                case TType.BOOL => {
                  success = {
                    _iprot.readBool()
                  }
                  _got_success = true
                }
                case _ => TProtocolUtil.skip(_iprot, _field.`type`)
              }
            }
            case _ =>
              TProtocolUtil.skip(_iprot, _field.`type`)
          }
          _iprot.readFieldEnd()
        }
      }
      _iprot.readStructEnd()
      if (!_got_term) throw new TProtocolException("Required field 'AppendEntriesResponseST' was not found in serialized data for struct AppendEntriesResponseST")
      if (!_got_success) throw new TProtocolException("Required field 'AppendEntriesResponseST' was not found in serialized data for struct AppendEntriesResponseST")
      new Immutable(
        term,
        success
      )
    }
  }

  /**
   * The default read-only implementation of AppendEntriesResponseST.  You typically should not need to
   * directly reference this class; instead, use the AppendEntriesResponseST.apply method to construct
   * new instances.
   */
  class Immutable(
    val term: Int,
    val success: Boolean
  ) extends AppendEntriesResponseST

  /**
   * This Proxy trait allows you to extend the AppendEntriesResponseST trait with additional state or
   * behavior and implement the read-only methods from AppendEntriesResponseST using an underlying
   * instance.
   */
  trait Proxy extends AppendEntriesResponseST {
    protected def _underlying_AppendEntriesResponseST: AppendEntriesResponseST
    override def term: Int = _underlying_AppendEntriesResponseST.term
    override def success: Boolean = _underlying_AppendEntriesResponseST.success
  }
}

trait AppendEntriesResponseST extends ThriftStruct
  with Product2[Int, Boolean]
  with java.io.Serializable
{
  import AppendEntriesResponseST._


  def term: Int
  def success: Boolean

  def _1 = term
  def _2 = success


  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): AppendEntriesResponseST =
    _fieldId match {
      case 1 => copy(term = 0)
      case 2 => copy(success = false)
      case _ => this
    }

  override def write(_oprot: TProtocol) {
    AppendEntriesResponseST.validate(this)
    _oprot.writeStructBegin(Struct)
    if (true) {
      val term_item = term
      _oprot.writeFieldBegin(TermField)
      _oprot.writeI32(term_item)
      _oprot.writeFieldEnd()
    }
    if (true) {
      val success_item = success
      _oprot.writeFieldBegin(SuccessField)
      _oprot.writeBool(success_item)
      _oprot.writeFieldEnd()
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    term: Int = this.term, 
    success: Boolean = this.success
  ): AppendEntriesResponseST =
    new Immutable(
      term,
      success
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[AppendEntriesResponseST]

  override def equals(other: Any): Boolean =
    _root_.scala.runtime.ScalaRunTime._equals(this, other)

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => term
    case 1 => success
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "AppendEntriesResponseST"
}