/**
 * Generated by Scrooge
 *   version: ?
 *   rev: ?
 *   built at: ?
 */
package ckite.rpc.thrift

import com.twitter.scrooge.{
  ThriftException, ThriftStruct, ThriftStructCodec3}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object RequestVoteResponseST extends ThriftStructCodec3[RequestVoteResponseST] {
  val Struct = new TStruct("RequestVoteResponseST")
  val CurrentTermField = new TField("currentTerm", TType.I32, 1)
  val CurrentTermFieldManifest = implicitly[Manifest[Int]]
  val GrantedField = new TField("granted", TType.BOOL, 2)
  val GrantedFieldManifest = implicitly[Manifest[Boolean]]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: RequestVoteResponseST) {
  }

  override def encode(_item: RequestVoteResponseST, _oproto: TProtocol) { _item.write(_oproto) }
  override def decode(_iprot: TProtocol): RequestVoteResponseST = Immutable.decode(_iprot)

  def apply(
    currentTerm: Int,
    granted: Boolean
  ): RequestVoteResponseST = new Immutable(
    currentTerm,
    granted
  )

  def unapply(_item: RequestVoteResponseST): Option[Product2[Int, Boolean]] = Some(_item)

  object Immutable extends ThriftStructCodec3[RequestVoteResponseST] {
    override def encode(_item: RequestVoteResponseST, _oproto: TProtocol) { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): RequestVoteResponseST = {
      var currentTerm: Int = 0
      var _got_currentTerm = false
      var granted: Boolean = false
      var _got_granted = false
      var _done = false
      _iprot.readStructBegin()
      while (!_done) {
        val _field = _iprot.readFieldBegin()
        if (_field.`type` == TType.STOP) {
          _done = true
        } else {
          _field.id match {
            case 1 => { /* currentTerm */
              _field.`type` match {
                case TType.I32 => {
                  currentTerm = {
                    _iprot.readI32()
                  }
                  _got_currentTerm = true
                }
                case _ => TProtocolUtil.skip(_iprot, _field.`type`)
              }
            }
            case 2 => { /* granted */
              _field.`type` match {
                case TType.BOOL => {
                  granted = {
                    _iprot.readBool()
                  }
                  _got_granted = true
                }
                case _ => TProtocolUtil.skip(_iprot, _field.`type`)
              }
            }
            case _ =>
              TProtocolUtil.skip(_iprot, _field.`type`)
          }
          _iprot.readFieldEnd()
        }
      }
      _iprot.readStructEnd()
      if (!_got_currentTerm) throw new TProtocolException("Required field 'RequestVoteResponseST' was not found in serialized data for struct RequestVoteResponseST")
      if (!_got_granted) throw new TProtocolException("Required field 'RequestVoteResponseST' was not found in serialized data for struct RequestVoteResponseST")
      new Immutable(
        currentTerm,
        granted
      )
    }
  }

  /**
   * The default read-only implementation of RequestVoteResponseST.  You typically should not need to
   * directly reference this class; instead, use the RequestVoteResponseST.apply method to construct
   * new instances.
   */
  class Immutable(
    val currentTerm: Int,
    val granted: Boolean
  ) extends RequestVoteResponseST

  /**
   * This Proxy trait allows you to extend the RequestVoteResponseST trait with additional state or
   * behavior and implement the read-only methods from RequestVoteResponseST using an underlying
   * instance.
   */
  trait Proxy extends RequestVoteResponseST {
    protected def _underlying_RequestVoteResponseST: RequestVoteResponseST
    override def currentTerm: Int = _underlying_RequestVoteResponseST.currentTerm
    override def granted: Boolean = _underlying_RequestVoteResponseST.granted
  }
}

trait RequestVoteResponseST extends ThriftStruct
  with Product2[Int, Boolean]
  with java.io.Serializable
{
  import RequestVoteResponseST._


  def currentTerm: Int
  def granted: Boolean

  def _1 = currentTerm
  def _2 = granted


  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is subtracked
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): RequestVoteResponseST =
    _fieldId match {
      case 1 => copy(currentTerm = 0)
      case 2 => copy(granted = false)
      case _ => this
    }

  override def write(_oprot: TProtocol) {
    RequestVoteResponseST.validate(this)
    _oprot.writeStructBegin(Struct)
    if (true) {
      val currentTerm_item = currentTerm
      _oprot.writeFieldBegin(CurrentTermField)
      _oprot.writeI32(currentTerm_item)
      _oprot.writeFieldEnd()
    }
    if (true) {
      val granted_item = granted
      _oprot.writeFieldBegin(GrantedField)
      _oprot.writeBool(granted_item)
      _oprot.writeFieldEnd()
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    currentTerm: Int = this.currentTerm, 
    granted: Boolean = this.granted
  ): RequestVoteResponseST =
    new Immutable(
      currentTerm,
      granted
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[RequestVoteResponseST]

  override def equals(other: Any): Boolean =
    _root_.scala.runtime.ScalaRunTime._equals(this, other)

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => currentTerm
    case 1 => granted
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "RequestVoteResponseST"
}